### ISSUE TITLE
Use plug instead of Cowboy directly

### ISSUE THREAD

**Issue by mgwidmann** [siscia/numerino#2]
https://github.com/elixir-lang/plug

**Comment by siscia** [comment]
What we will get from this change ? Why you believe it is better than using directly cowboy ?

**Comment by mgwidmann** [comment]
More readable and manageable code for one. Plug is also an abstraction layer so it would be easier in the future to change to a different web server if something better comes up. 

Also, returning EOF for any response is not an acceptable web standard. Return a proper HTTP status that represents the error and optionally provide a JSON body. Almost no tools out there in any language are going to handle EOFs very well, it puts additional burden on the client.

**Comment by siscia** [comment]
You are definitely right about the EOF, I am thinking about returning only the code 204, do you agree ?

About plug vs cowboy I am not sure at all, I don't think that something better than cowboy will come out, plug itself use cowboy I don't see the need of another layer, also I am not very comfortable with plug, I think that I will be better sticking at what I know... Thought ?

**Comment by mgwidmann** [comment]
Compare [a plug implementation of a simple get](https://github.com/elixir-lang/plug#the-plug-router) vs [your implementation using cowboy directly](https://github.com/siscia/numerino/blob/master/lib/web_bind.ex#L16) and tell me which one is more readable and more maintainable. Plug is very simple and straight forward to use.

Imagine your `web_bind.ex` file looking like this instead: (Note: untested, just an example)

``` elixir
defmodule Numerino.HTTPBench do
  use Plug.Router
  plug Plug.Logger
  plug :match
  plug :dispatch
  plug Plug.Parsers.JSON, json_decoder: JSON

  get "/" do
    conn
    |> put_resp_content_type("application/json")
    |> respond_to_pop(Numerino.pop)   # GenServer client method for poping
  end

  def respond_to_pop(conn, nil), do: send_resp(conn, 204, "")
  def respond_to_pop(conn, data), do: send_resp(conn, 200, JSON.encode!(data))

  post "/" do
    conn
    |> put_resp_content_type("application/json")
    |> send_resp(200, Numerino.push(conn.params)) # GenServer client method for pushing
  end

  match _ do
    send_resp(conn, 404, "Not found.")
  end
end
```

First of all your push/pop code is now separated into a separate process holding its own state. This is a huge improvement since web requests crashing no longer destroy state. Second, you can leverage all the available plugs out there that have been written so you don't have to do things like the logger or parsing the request body and merging with query params. The current implementation expects params  to be in the body, and while thats normal, theres no reason why they can't be in the query string.

**Comment by mgwidmann** [comment]
Actually now that I see that code, I think you can even do 

```
  plug :put_resp_content_type, "application/json"
```

and then that line wouldn't even be necesary... Both your GET and POST would be one liners.

**Comment by siscia** [comment]
I will definitely look at plug, if you want to send a PR you are definitely welcome.

However, it seems pretty magic, while cowboy is extremely linear...
